import type { ImageMetadata } from 'astro';
import type { Localized } from '@/i18n/config';

import anour from '@/assets/team/anour-dafaalla.jpg';
import aamer from '@/assets/team/aamer-mihaysi.jpg';
import tamir from '@/assets/team/tamir-s.jpg';
import salma from '@/assets/team/salma-mahgoub.jpg';
import altayeb from '@/assets/team/mohamed-altayeb.jpg';
import elmustafa from '@/assets/team/mohammed-el-mustafa.jpg';
import gafer from '@/assets/team/mustafa-gafer.jpg';

/**
 * Team roster. Names, roles and LinkedIn profiles come from the owner's own team list and are
 * kept exactly as given: never rename a role or invent a title. Names and roles stay in Latin
 * script on every page (rendered inside translate="no"). `summary` is a short professional
 * summary of the owner's biography, with every fact kept and no claim added.
 *
 * Portraits are generated by scripts/build-team-portraits.mjs (720x900, 4:5, one shared tone).
 */
export interface Person {
  slug: string;
  name: string;
  role: string;
  group: 'founders' | 'team';
  linkedin: string;
  summary: Localized;
  portrait: ImageMetadata;
}

export const team: Person[] = [
  {
    slug: 'anour-dafaalla',
    name: 'Dr. Anour Ahmed Dafaalla',
    role: 'Co-Founder & AI Researcher',
    group: 'founders',
    linkedin: 'https://www.linkedin.com/in/anwarking/',
    summary: {
      en: 'Works with emerging technologies, with a focus on practical AI implementations and advanced machine learning education.',
      ar: 'يعمل على التقنيات الناشئة، مع تركيز على التطبيقات العملية للذكاء الاصطناعي وتعليم التعلّم الآلي المتقدم.',
    },
    portrait: anour,
  },
  {
    slug: 'aamer-mihaysi',
    name: 'Aamer Mihaysi',
    role: 'Co-Founder & AI Engineer',
    group: 'founders',
    linkedin: 'https://www.linkedin.com/in/mihaysi/',
    summary: {
      en: 'Specializes in agentic cognitive systems, with a strong background in generative AI and maritime AI technologies.',
      ar: 'متخصص في الأنظمة الإدراكية الوكيلية، وله خلفية قوية في الذكاء الاصطناعي التوليدي وتقنيات الذكاء الاصطناعي البحرية.',
    },
    portrait: aamer,
  },
  {
    slug: 'tamir-s',
    name: 'Dr. Tamir S.',
    role: 'SIEM and Cyber Security Engineer',
    group: 'team',
    linkedin: 'https://www.linkedin.com/in/allamiro/',
    summary: {
      en: 'Deep expertise in designing secure architectures, detecting threats and protecting critical data infrastructure.',
      ar: 'خبرة عميقة في تصميم البُنى الآمنة وكشف التهديدات وحماية البنية التحتية الحيوية للبيانات.',
    },
    portrait: tamir,
  },
  {
    slug: 'salma-mahgoub',
    name: 'Salma Mahgoub',
    role: 'Sales and Marketing Specialist',
    group: 'team',
    linkedin: 'https://www.linkedin.com/in/salma-mahgoub-43b37b125/',
    summary: {
      en: 'Committed to strategic business development, customer engagement and targeted marketing campaigns.',
      ar: 'تركّز على تطوير الأعمال الاستراتيجي والتواصل مع العملاء والحملات التسويقية الموجَّهة.',
    },
    portrait: salma,
  },
  {
    slug: 'mohamed-altayeb',
    name: 'Mohamed Altayeb',
    role: 'AI Researcher',
    group: 'team',
    linkedin: 'https://www.linkedin.com/in/mohammad2012191/',
    summary: {
      en: 'Data scientist focused on applied machine learning, competitive modeling and real-world AI experimentation.',
      ar: 'عالِم بيانات يركّز على التعلّم الآلي التطبيقي والنمذجة التنافسية والتجارب الواقعية في الذكاء الاصطناعي.',
    },
    portrait: altayeb,
  },
  {
    slug: 'mohammed-el-mustafa',
    name: 'Mohammed El-Mustafa',
    role: 'Senior Software Engineer',
    group: 'team',
    linkedin: 'https://www.linkedin.com/in/mohammed-el-mustafa-ahmed/',
    summary: {
      en: 'Mathematician with expertise in high-scale backend systems, distributed architecture and performance optimization.',
      ar: 'عالِم رياضيات بخبرة في الأنظمة الخلفية واسعة النطاق والعمارة الموزّعة وتحسين الأداء.',
    },
    portrait: elmustafa,
  },
  {
    slug: 'mustafa-gafer',
    name: 'Mustafa Gafer',
    role: 'Information Systems Expert',
    group: 'team',
    linkedin: 'https://www.linkedin.com/in/mustafagafar/',
    summary: {
      en: 'CISSP-certified. Advises on enterprise applications, cybersecurity governance and data management.',
      ar: 'حاصل على شهادة CISSP، ويقدّم الاستشارات في تطبيقات المؤسسات وحوكمة الأمن السيبراني وإدارة البيانات.',
    },
    portrait: gafer,
  },
];

export const founders = team.filter((p) => p.group === 'founders');
export const teamMembers = team.filter((p) => p.group === 'team');
