import type { ImageMetadata } from 'astro';
import type { Localized } from '@/i18n/config';

import anour from '@/assets/team/anour-dafaalla.jpg';
import aamer from '@/assets/team/aamer-mihaysi.jpg';
import tamir from '@/assets/team/tamir-s.jpg';
import salma from '@/assets/team/salma-mahgoub.jpg';
import adil from '@/assets/team/mohammed-adil-yassin.jpg';
import abdalgader from '@/assets/team/abdalgader-abubaker.jpg';
import altayeb from '@/assets/team/mohamed-altayeb.jpg';
import elmustafa from '@/assets/team/mohammed-el-mustafa.jpg';
import gafer from '@/assets/team/mustafa-gafer.jpg';
import samahir from '@/assets/team/samahir-elzaki.jpg';
import maram from '@/assets/team/maram-mohamed.jpg';
import hiba from '@/assets/team/hiba-eljozouly.jpg';

/**
 * Team roster. Names, roles and LinkedIn profiles come from the owner's own team list and are
 * kept exactly as given: never rename a role or invent a title. Names and roles stay in Latin
 * script on every page (rendered inside translate="no"). `summary` is a short professional
 * summary of the owner's biography, with every fact kept and no claim added.
 *
 * Portraits are generated by scripts/build-team-portraits.mjs (720x900, 4:5, one shared tone).
 */
export interface Person {
  slug: string;
  name: string;
  role: string;
  group: 'founders' | 'team';
  linkedin: string;
  summary: Localized;
  portrait: ImageMetadata;
}

export const team: Person[] = [
  {
    slug: 'anour-dafaalla',
    name: 'Dr. Anour Ahmed Dafaalla',
    role: 'Co-Founder & AI Researcher',
    group: 'founders',
    linkedin: 'https://www.linkedin.com/in/anwarking/',
    summary: {
      en: 'Works with emerging technologies, with a focus on practical AI implementations and advanced machine learning education.',
      ar: 'يعمل على التقنيات الناشئة، مع تركيز على التطبيقات العملية للذكاء الاصطناعي وتعليم التعلّم الآلي المتقدم.',
    },
    portrait: anour,
  },
  {
    slug: 'aamer-mihaysi',
    name: 'Aamer Mihaysi',
    role: 'Co-Founder & AI Engineer',
    group: 'founders',
    linkedin: 'https://www.linkedin.com/in/mihaysi/',
    summary: {
      en: 'Specializes in agentic cognitive systems, with a strong background in generative AI and maritime AI technologies.',
      ar: 'متخصص في الأنظمة الإدراكية الوكيلية، وله خلفية قوية في الذكاء الاصطناعي التوليدي وتقنيات الذكاء الاصطناعي البحرية.',
    },
    portrait: aamer,
  },
  {
    slug: 'tamir-s',
    name: 'Dr. Tamir S.',
    role: 'SIEM and Cyber Security Engineer',
    group: 'team',
    linkedin: 'https://www.linkedin.com/in/allamiro/',
    summary: {
      en: 'Deep expertise in designing secure architectures, detecting threats and protecting critical data infrastructure.',
      ar: 'خبرة عميقة في تصميم البُنى الآمنة وكشف التهديدات وحماية البنية التحتية الحيوية للبيانات.',
    },
    portrait: tamir,
  },
  {
    slug: 'salma-mahgoub',
    name: 'Salma Mahgoub',
    role: 'Sales and Marketing Specialist',
    group: 'team',
    linkedin: 'https://www.linkedin.com/in/salma-mahgoub-43b37b125/',
    summary: {
      en: 'Committed to strategic business development, customer engagement and targeted marketing campaigns.',
      ar: 'تركّز على تطوير الأعمال الاستراتيجي والتواصل مع العملاء والحملات التسويقية الموجَّهة.',
    },
    portrait: salma,
  },
  {
    slug: 'mohammed-adil-yassin',
    name: 'Mohammed Adil Yassin',
    role: 'AI Consultant',
    group: 'team',
    linkedin: 'https://www.linkedin.com/in/mohammed-adil-yassin-b6a835111/',
    summary: {
      en: 'Focused on strategic AI adoption, business transformation and the integration of practical AI solutions.',
      ar: 'يركّز على تبنّي الذكاء الاصطناعي استراتيجيًا، والتحوّل في الأعمال، ودمج حلول الذكاء الاصطناعي العملية.',
    },
    portrait: adil,
  },
  {
    slug: 'abdalgader-abubaker',
    name: 'Abdalgader Abubaker',
    role: 'Senior AI Engineer',
    group: 'team',
    linkedin: 'https://www.linkedin.com/in/abdalgader-abubaker/',
    summary: {
      en: 'Former Meta AI Resident, specializing in graph neural networks, self-supervised learning and large-scale model development.',
      ar: 'مقيم سابق في Meta AI، متخصص في الشبكات العصبية الرسومية والتعلّم ذاتي الإشراف وتطوير النماذج واسعة النطاق.',
    },
    portrait: abdalgader,
  },
  {
    slug: 'mohamed-altayeb',
    name: 'Mohamed Altayeb',
    role: 'AI Researcher',
    group: 'team',
    linkedin: 'https://www.linkedin.com/in/mohammad2012191/',
    summary: {
      en: 'Data scientist focused on applied machine learning, competitive modeling and real-world AI experimentation.',
      ar: 'عالِم بيانات يركّز على التعلّم الآلي التطبيقي والنمذجة التنافسية والتجارب الواقعية في الذكاء الاصطناعي.',
    },
    portrait: altayeb,
  },
  {
    slug: 'mohammed-el-mustafa',
    name: 'Mohammed El-Mustafa',
    role: 'Senior Software Engineer',
    group: 'team',
    linkedin: 'https://www.linkedin.com/in/mohammed-el-mustafa-ahmed/',
    summary: {
      en: 'Mathematician with expertise in high-scale backend systems, distributed architecture and performance optimization.',
      ar: 'عالِم رياضيات بخبرة في الأنظمة الخلفية واسعة النطاق والعمارة الموزّعة وتحسين الأداء.',
    },
    portrait: elmustafa,
  },
  {
    slug: 'mustafa-gafer',
    name: 'Mustafa Gafer',
    role: 'Information Systems Expert',
    group: 'team',
    linkedin: 'https://www.linkedin.com/in/mustafagafar/',
    summary: {
      en: 'CISSP-certified. Advises on enterprise applications, cybersecurity governance and data management.',
      ar: 'حاصل على شهادة CISSP، ويقدّم الاستشارات في تطبيقات المؤسسات وحوكمة الأمن السيبراني وإدارة البيانات.',
    },
    portrait: gafer,
  },
  {
    slug: 'samahir-elzaki',
    name: 'Samahir Elzaki',
    role: 'MSc Researcher',
    group: 'team',
    linkedin: 'https://www.linkedin.com/in/samahir-elzaki-701825292/',
    summary: {
      en: 'Researcher in IT management and data analyst, exploring generative AI, human-AI collaboration and digital transformation strategies.',
      ar: 'باحثة في إدارة تقنية المعلومات ومحلّلة بيانات، تستكشف الذكاء الاصطناعي التوليدي والتعاون بين الإنسان والذكاء الاصطناعي واستراتيجيات التحوّل الرقمي.',
    },
    portrait: samahir,
  },
  {
    slug: 'maram-mohamed',
    name: 'Maram A. Mohamed',
    role: 'PhD Researcher',
    group: 'team',
    linkedin: 'https://www.linkedin.com/in/maram-a-mohamed-5a2720b0/',
    summary: {
      en: 'Researcher at the Insight Centre (DCU) specializing in computer vision and generative AI, with a focus on accessible technology such as sign language translation systems.',
      ar: 'باحثة في Insight Centre (DCU) متخصصة في الرؤية الحاسوبية والذكاء الاصطناعي التوليدي، وتركّز على التقنيات الميسّرة مثل أنظمة ترجمة لغة الإشارة.',
    },
    portrait: maram,
  },
  {
    slug: 'hiba-eljozouly',
    name: 'Hiba Eljozouly',
    role: 'Founder of GDG',
    group: 'team',
    linkedin: 'https://www.linkedin.com/in/hibaeljozouly',
    summary: {
      en: 'Founder and organizer of GDG on Campus at SUST, and a cloud and machine learning enthusiast who supports students through technology community building and industry connections.',
      ar: 'مؤسِّسة ومنظِّمة GDG on Campus في SUST، ومهتمة بالحوسبة السحابية والتعلّم الآلي، وتدعم الطلاب ببناء المجتمعات التقنية وربطهم بالصناعة.',
    },
    portrait: hiba,
  },
];

export const founders = team.filter((p) => p.group === 'founders');
export const teamMembers = team.filter((p) => p.group === 'team');
